import { renderSystemsList } from "../chekboxesList";
import { calculatePrice } from "../PriceCalculator";

export let systemsList: CheckboxItem[] = [
  {
    id: "sys_1",
    name: "سیستم حسابداری",
    price: "99000000",
    checked: true,
    pre: [],
    preSub: [],
    preOR: [],
    preSubOR: [],
    post: [],
    postSub: [],
    textForModal: [],
  },
  {
    id: "sys_2",
    name: "سیستم دارایی ثابت",
    price: "167000000",
    checked: false,
    pre: [],
    preSub: [],
    preOR: [],
    preSubOR: [],
    post: [],
    postSub: [],
    textForModal: [],
  },
  {
    id: "sys_3",
    name: "سیستم دریافت و پرداخت",
    price: "156000000",
    checked: false,
    post: ["sys_6","sys_8", "sys_11"],
    pre: [],
    preSub: [],
    preOR: [],
    preSubOR: [],
    postSub: ["subSys_11", "subSys_12"],
    textForModal: [""],
  },
  {
    id: "sys_4",
    name: "سیستم تامین کنندگان و انبار تولیدی",
    price: "210000000",
    checked: false,
    pre: [],
    preSub: [],
    preOR: [],
    preSubOR: [],
    post: ["sys_6","sys_10", "sys_11", "sys_14"],
    postSub: ["subSys_3", "subSys_6", "subSys_7", "subSys_12", "subSys_13"],
    textForModal: [],
  },
  {
    id: "sys_5",
    name: "سیستم حقوق و دستمزد",
    price: "204000000",
    checked: false,
    pre: [],
    preSub: [],
    preOR: [],
    preSubOR: [],
    postSub: [],
    textForModal: [],
    post: [],
  },
  {
    id: "sys_6",
    name: "سیستم مشتریان و فروش",
    price: "210000000",
    checked: false,
    post: ["sys_11", "sys_15"],
    pre: ["sys_3"],
    preSub: [],
    preOR: ["sys_4","sys_7"],
    preSubOR: [],
    postSub: ["subSys_2", "subSys_10", "subSys_12"],
    textForModal: ["سیستم دریافت پرداخت","سیستم تامین کنندگان و انبار تولیدی یا سیستم تامین کنندگان و انبار بازرگانی"],
  },
  {
    id: "sys_7",
    name: "سیستم تامین کنندگان و انبار بازرگانی",
    price: "185000000",
    checked: false,
    post: ["sys_6","sys_11", "sys_14"],
    pre: [],
    preSub: [],
    preOR: [],
    preSubOR: [],
    postSub: [
      "subSys_3",
      "subSys_6",
      "subSys_7",
      "subSys_12",
      "subSys_8",
      "subSys_13",
    ],
    textForModal: [],
  },
  {
    id: "sys_8",
    name: "سیستم فروش خدماتی",
    price: "195000000",
    checked: false,
    pre: ["sys_3"],
    preSub: [],
    post: ["sys_15"],
    postSub: ["subSys_2", "subSys_10"],
    preOR: [],
    preSubOR: [],
    textForModal: ["سیستم دريافت و پرداخت"]
  },
  {
    id: "sys_9",
    name: "حسابداری پیمانکاری",
    price: "235000000",
    checked: false,
    post: ["sys_15"],
    pre: [],
    preSub: [],
    preOR: [],
    preSubOR: [],
    postSub: [],
    textForModal: [],
  },
  {
    id: "sys_10",
    name: "سیستم تولید",
    price: "203000000",
    checked: false,
    pre: ["sys_4"],
    preSub: [],
    post: [],
    preOR: [],
    preSubOR: [],
    postSub: [],
    textForModal: ["سیستم تامین کنندگان و انبار تولیدی"],
  },
  {
    id: "sys_11",
    name: "سیستم سفارش گیری",
    price: "252000000",
    checked: false,
    pre: ["sys_3","sys_6"],
    preSub: ["subSys_2"],
    preOR: ["sys_4","sys_7"],
    preSubOR: [],
    post: ["sys_12"],
    postSub: ["subSys_9"],
    textForModal: [
      "سیستم دریافت و پرداخت",
      "سیستم تامین کنندگان و انبار تولیدی یا سیستم تامین کنندگان و انبار بازرگانی",
      "سیستم مشتریان و فروش",
      "فروش پیشرفته",
    ],
  },
  {
    id: "sys_12",
    name: "سیستم پخش سرد",
    price: "405000000",
    checked: false,
    pre: ["sys_11"],

    preSub: ["subSys_2"],
    preOR: [],
    preSubOR: [],
    post: [],
    postSub: [],
    textForModal: ["سیستم سفارش گیری", "فروش پیشرفته"],
  },
  {
    id: "sys_13",
    name: "سیستم پخش گرم",
    price: "405000000",
    checked: false,
    pre: [],

    preSub: ["subSys_2"],
    preOR: [],
    preSubOR: [],
    post: [],
    postSub: [],
    textForModal: ["فروش پیشرفته"],
  },
  {
    id: "sys_14",
    name: "سیستم سفارشات و خرید خارجی",
    price: "240000000",
    checked: false,
    pre: [],
    preSub: [],
    preOR: ["sys_4", "sys_7"],
    preSubOR: [],
    post: [],
    postSub: [],
    textForModal: [
      "سیستم تامین کنندگان و انبار تولیدی یا سیستم تامین کنندگان و انبار بازرگانی",
    ],
  },
  {
    id: "sys_15",
    name: "سیستم سامانه مؤدیان",
    price: "99000000",
    checked: false,
    pre: [],
    preSub: [],
    preOR: ["sys_6", "sys_8", "sys_9"],
    preSubOR: [],
    post: [],
    postSub: [],
    textForModal: ["سیستم مشتریان و فروش یا فروش خدماتی یا حسابداری پیمانکاری"],
  },
];

export function updateSystemsList(updatedItem: CheckboxItem) {
  const index = systemsList.findIndex((item) => item.id === updatedItem.id);
  if (index !== -1) {
    systemsList[index] = updatedItem;
  }

  renderSystemsList(systemsList);
  calculatePrice();
}

export function setNewSystemsList(newList: CheckboxItem[]) {
  systemsList = newList;
  renderSystemsList(systemsList);
  calculatePrice();
}
